### PR TITLE
Implementation of new hand written poisson

### LINKED ISSUE #159: Split hand written poisson example into small pieces
The current version of the hand written poisson example is implemented in a monolithic block of code which makes it very difficult to profile. The new implementation should consider separation of concerns and have dedicated functions for every step.

### PR DESCRIPTION
**Pull request by Cmurilochem**
Closes #159.

### CODE REVIEW

**Comment by Cmurilochem** [comment]
@fverdugo and @raar1. The first draft of the new implementation of our hand written poisson is ready. But there are lots of things that we can still optimize.

For example, in [assemble_fill](https://github.com/GalerkinToolkit/GalerkinToolkit.jl/blob/05bb75ad09058e341d1cc0c66e7467751bc2cbc2/GalerkinToolkitExamples/src/poisson.jl#L373) and [integrate_error_norms](https://github.com/GalerkinToolkit/GalerkinToolkit.jl/blob/05bb75ad09058e341d1cc0c66e7467751bc2cbc2/GalerkinToolkitExamples/src/poisson.jl#L270C10-L270C31) (and [export_results](https://github.com/GalerkinToolkit/GalerkinToolkit.jl/blob/05bb75ad09058e341d1cc0c66e7467751bc2cbc2/GalerkinToolkitExamples/src/poisson.jl#L213) to a lesser extent) I noticed that the core loops have nearly the same structure and there is a lot of code repetition. Maybe something to look at.

**Comment by fverdugo** [comment]
Perfect! @Cmurilochem can you please remove the old version?

**Comment by Cmurilochem** [comment]
> Perfect! @Cmurilochem can you please remove the old version?

Yes, of course. Done!

**Comment by fverdugo** [comment]
We are "bending the line" 😀

Screenshot from 2024-12-11 09-43-32

**Pull request merged**
