### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by fverdugo**
* Add a basic skeleton for the documentation, including, Examples, Manual, and Reference.
* Add a first example to set the tone/style for the examples. (These will be short examples, instead of full Tutorials). For the great details we will have the Manual and the docstrings in Reference.

This makes PR #87 obsolete.

cc @Cmurilochem @raar1

### CODE REVIEW

**Comment by fverdugo** [comment]
@Cmurilochem Can you please fix the docs build? I did not manage to get GLMakie working on GH Actions. It works on my computer though.

**Comment by Cmurilochem** [comment]
> @Cmurilochem Can you please fix the docs build? I did not manage to get GLMakie working on GH Actions. It works on my computer though.

Hi @fverdugo. Thanks for the ideas put into this PR; doc structure looks amazing and it worked locally here also for me. I will have a look at it today.

**Comment by fverdugo** [comment]
This seems to be a hard one. Have you tried this?

https://discourse.julialang.org/t/ci-fails-to-build-glmakie-dependency/80125/4

**Comment by Cmurilochem** [comment]
> This seems to be a hard one. Have you tried this?
> 
> https://discourse.julialang.org/t/ci-fails-to-build-glmakie-dependency/80125/4

Thanks @fverdugo. Yes, I was actually trying to adapt the solution provided in the above link. I will try once again this morning. The GitHub action runners look strangely "lazy" today or maybe I made a mistake in the file I still did not realize.

**Comment by fverdugo** [comment]
Hi @Cmurilochem  the error in the examples is bc we published a new version in partitioned solvers. Add a compat entry in the project file of the examples to use PartitionedSolvers v0.2,0.

**Comment by Cmurilochem** [comment]
> Hi @Cmurilochem the error in the examples is bc we published a new version in partitioned solvers. Add a compat entry in the project file of the examples to use PartitionedSolvers v0.2,0.

Thanks @fverdugo for letting me know. I will take care of this. Also, the doc is working with a hack and I will now clean up a bit.

**Comment by Cmurilochem** [comment]
@fverdugo. I will take this task as done. I decided to build the docs via `include(docs/make.jl)` instead of using `julia-actions/julia-docdeploy`. See you later this afternoon.

**Pull request merged**
